### ISSUE TITLE
Database file path is not set in the server configuration file.

### ISSUE THREAD

**Issue by josephwambura** [libgenapps/LibgenServer#2]
Exception: Database file path is not set in the server configuration file.
LibgenServer.Web.Models.MainModel..ctor(IOptionsMonitor<ServerConfiguration> optionsMonitor, FileExtensionContentTypeProvider fileExtensionContentTypeProvider) in MainModel.cs, line 35

**Comment by libgenapps** [comment]
You need to use LibgenServer.Cli app (libgen.exe) to set it up first. Also keep in mind that the project is in an early development stage with no setup instructions or support yet.
